### ISSUE TITLE
Make sure the driver can be used at Fermilab

### ISSUE THREAD

**Issue by rneswold** [fermi-controls/fe-drv-acsys-states#1]
During the 2022 shutdown, I want to migrate the STATES service from VME/MOOC to ACSys/FE. I contend, since this service was a pure software project, it never should have used expensive VME/VxWorks resources. By migrating to ACSys/FE, we use less expensive server hardware (which are more powerful than our VME processors!) and free Linux licenses. It has been used by NOvA for many years, but the driver doesn't contain 100% of the features of the MOOC server.

This issue, and the ensuring discussion, is to understand the details and track the progress of the migration.

## MOOC Implementation

This is what we know about the current MOOC system:

- It queries the database when starting to get the set of devices it owns. This lets it restore its state (both the devices and their last setting) after a reboot.
- A state device can be set through one of two interfaces:
  - ACNET settings
  - FSMSET handle
- State devices can be enabled/disabled through basic control.
- State device updates are sent via two methods:
  - multicast on address 239.128.1.5:50090
  - via the FSMSET handle to registered clients
- A read request of 2 bytes results in the 16 bit value being returned. If the request is for 4 bytes, a floating point representation is returned (why?!)

The source code defines the OID and Class code to be 76. The SSDN for all 688 state devices use `4C` as the OID value. This is the layout of the SSDN:

`0000` / `004C` / `min` / `max`

This driver handles its devices in a nonstandard way: all devices have the "same" SSDN (except for the min/max fields). Normally each device gets its own OID but this driver looks at the DI field of the request to know which device is being handled. That means there are a lot of duplicate SSDNs (and people are ignoring the warnings from DABBEL.) There are 2,763 SSDN records across the 688 state devices. However, there are only 100 unique SSDNs!

## Current ACSys/FE Implementation

The current (Sept, 2022) version of the ACSys/FE driver has these features:

- The driver doesn't maintain persistent information. It doesn't query the database but, instead, builds its table as settings are made.
- A state device can be set through one of two interfaces:
  - ACNET settings
  - FSMSET handle
- State device updates are multicast on the STATES@STATES ACNET handle
- Readings are 2 bytes and simply return the 16 bit value of the device.

## Upshot

The MOOC driver supports the entire FSMSET service while the ACSys/FE driver only supports setting state devices. Whether the rest needs to be done can be discussed. The ACSys/FE doesn't restore its state after a restart but, instead, builds it back up as settings come in. The ACSys/FE is *vastly* simpler than the MOOC driver and shouldn't require restarts (this has been the case in the NOvA installation) so I don't think we need to add that complexity. ACSys/FE also only uses ACNET multicasts. We probably have UDP multicast listeners, so that feature will need to be added.

**Comment by rneswold** [comment]
So, as a first crack at a TO-DO list:

- [ ] Add missing, necessary features to driver
  - [ ] Multicast to `239.128.1.5:50090`
- [ ] Prep DABBEL scripts
  - [ ] Save DABBEL listing so the devices can be reverted
  - [ ] Create new DABBEL script that translates to the new system
- [ ] For testing, migrate one device
  - [ ] Use DABBEL to translate its SSDN and node (eventually it'll get put back to `STATE`)
  - [ ] Spin up the driver on the new system
  - [ ] Test the device
- [ ] Move the ACNET node name `STATE` to the IP address of the target, ACSys/FE system
- [ ] Run the DABBEL script to translate the rest of the devices

**Comment by rneswold** [comment]
Brian mentioned he thought LabView system require the STATE front-end send them state updates directly.

**Comment by beauremus** [comment]
It seems beneficial to isolate this specialized functionality into its own service. That allows STATES to focus on what it needs to do without exception, and it's easy to know what the new LabView STATES service is doing can be updated easily.

**Comment by rneswold** [comment]
Using `D88`, I see that there are 47 clients that want states forwarded to a device they own. Working through the list, I also found that 44 of them are obsolete! Of the remaining three, one is a test device (`V:TSTSET` -> `Z:TSTRCV`), the other is a device owned by an out of service, motion control front-end (`V:TEVCOL` -> `T:A48SQ`). The last appears to still be used (😩 so close!)

So we still need to forward `V:BOOCOL` to `B:BCOLSQ`.

As recommended by @beauremus, this special feature will be put into a different process -- outside of the STATE service. When this last use goes away, we can simply stop the task and not affect STATE.

**Comment by nicklausdj** [comment]
Does the Acsys version need to support the FSMSET stuff?
How many Labview front ends are there still?
Is there any useful "reading of the setting" that you'd want to download the settings for?
It seems like you wouldn't want to only enable multicast after the download is completed -- no reason to re-multicast previous done settings.

**Comment by mzs-fnal** [comment]
LinacVME & IRM FEs listen to the 239.128.1.5:50090 multicasts. That's how GETS32 on STATE changes work.

**Comment by rneswold** [comment]
> Does the Acsys version need to support the FSMSET stuff?

Java is the only user of FSMSET and they only use one of the type codes. The current driver supports it already.

> How many Labview front ends are there still?

I emailed Dave Slimmer and he says the LabView nodes are listening to the raw multicast. That's why 44 devices were removed from `D88`; they were LabView devices and have been obsoleted (but not removed from `D88`.)

> Is there any useful "reading of the setting" that you'd want to download the settings for? It seems like you wouldn't want to only enable multicast after the download is completed -- no reason to re-multicast previous done settings.

This driver isn't going to use SQL to get its set of devices. What it could do, however, is set all the state devices to have a setting record. When DWNLDD forwards the settings, it'll populate the table! If the entry isn't there, it won't multicast it.

**Comment by nicklausdj** [comment]
I looked at the erlang download code, and it doesn’t really have a way of asking it if the download has ever completed.
But it does recognize dthe “download completed” message and does have an internal state variable that  gets set.
We could add a function to interrogate that, or register to be notified when it is done so your driver could know, or something.
But nothing currently there.

Your scheme of the first is treated as a download would probably work.




From: Rich Neswold ***@***.***>
Date: Thursday, September 8, 2022 at 2:21 PM
To: fermi-controls/fe-drv-acsys-states ***@***.***>
Cc: Dennis J. Nicklaus ***@***.***>, Comment ***@***.***>
Subject: Re: [fermi-controls/fe-drv-acsys-states] Make sure the driver can be used at Fermilab (Issue #1)

Does the Acsys version need to support the FSMSET stuff?

Java is the only user of FSMSET and they only use one of the type codes. The current driver supports it already.

How many Labview front ends are there still?

I emailed Dave Slimmer and he says the LabView nodes are listening to the raw multicast. That's why 44 devices were removed from D88; they were LabView devices and have been obsoleted (but not removed from D88.)

Is there any useful "reading of the setting" that you'd want to download the settings for? It seems like you wouldn't want to only enable multicast after the download is completed -- no reason to re-multicast previous done settings.

This driver isn't going to use SQL to get its set of devices. What it could do, however, is set all the state devices to have a setting record. When DWNLDD forwards the settings, it'll populate the table! If the entry isn't there, it won't multicast it.

**Comment by rneswold** [comment]
Making these comments here because our Erlang framework isn't in GitHub yet.

- "register to be notified" -- I agree. We should have an announce service that posts interesting system events. Any Erlang process, including drivers, could register to receive these events in their message queue.
- The framework should see that a setting is coming from `DNLDD` and clear the `forward setting` flag. The STATE driver could use the flag as an indicator that this is an "initializing" setting rather than an update.

**Comment by nicklausdj** [comment]
Funny, I always thought that settings from dnldd had that forward flag off. But dnldd.cpp just uses dio_set_raw_c, which doesn't have that as option at all.

**Comment by rneswold** [comment]
State device support has been migrated to CLX24.

**Comment by nicklausdj** [comment]
That’s great!


From: Rich Neswold ***@***.***>
Date: Monday, September 26, 2022 at 4:24 PM
To: fermi-controls/fe-drv-acsys-states ***@***.***>
Cc: Dennis J. Nicklaus ***@***.***>, Comment ***@***.***>
Subject: Re: [fermi-controls/fe-drv-acsys-states] Make sure the driver can be used at Fermilab (Issue #1)

State device support has been migrated to CLX24.
